name: sasa_firebase
description:

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_database: ^10.5.3
  flutter_rating_bar: ^4.0.0
  firebase_auth: ^4.19.5


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true
  assets:
    - images/logo.png
    - images/iconlogo.png
    - images/drHitham.jpg


